apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name}}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name}}
    spec:
      containers:
      - name: {{ .Chart.Name}}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports: 
        - containerPort: 80
          name: nginx-port