apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: svc-{{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name:  http
      protocol: TCP
      port:  {{ .Values.service.port }}
      