apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool
  #  namespace: netology
  labels:
    app: busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: nfs-vol
              mountPath: /testfolder
      volumes:
        - name: nfs-vol
          persistentVolumeClaim:
            claimName: nfs-pvc
